id: playground-series-s5e6
name: Playground Series Season 5, Episode 6
competition_type: simple
awards_medals: false
prizes: null
description: mlebench/competitions/playground-series-s5e6/description.md

dataset:
  answers: playground-series-s5e6/prepared/private/test.csv
  sample_submission: playground-series-s5e6/prepared/public/sample_submission.csv

grader:
  name: map-at-3
  grade_fn: mlebench.competitions.playground-series-s5e6.grade:grade

preparer: mlebench.competitions.playground-series-s5e6.prepare:prepare
