id: playground-series-s5e12
name: Playground Series Season 5, Episode 12
competition_type: simple
awards_medals: false
prizes: null
description: mlebench/competitions/playground-series-s5e12/description.md

dataset:
  answers: playground-series-s5e12/prepared/private/test.csv
  sample_submission: playground-series-s5e12/prepared/public/sample_submission.csv

grader:
  name: roc-auc
  grade_fn: mlebench.competitions.playground-series-s5e12.grade:grade

preparer: mlebench.competitions.playground-series-s5e12.prepare:prepare
